server:
  port: 8080
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto

# Настройки CORS
cors:
  allowed-origin: "https://hr-analyzer.sophia-lab.ru"

# Настройки OpenAPI/Swagger
openapi:
  server-url: "https://hr-analyzer.sophia-lab.ru"